fin = open("config.xml", "rt")
data = fin.read()
data = data.replace('<DM name="ViewName" val="IGD.AU1"/>'+"\n"+'<DM name="Enable" val="0"/>', '<DM name="ViewName" val="IGD.AU1"/>'+"\n"+'<DM name="Enable" val="1"/>')
data = data.replace('<DM name="SwitchShellEnable" val="0"/>', '<DM name="SwitchShellEnable" val="1"/>')
fin.close()
fin = open("config.xml", "wt")
fin.write(data)
fin.close()